---
- name: nginx install & start service
  hosts: all
  become: true

  tasks:
  - name: install nginx
    yum:
      name: nginx
      state: latest

  - name: start nginx
    service:
      name: nginx
      state: started

  - name: web.html copy
    template:
      src: /root/github/web.html
      dest: /usr/share/nginx/html/web.html
      owner: root
      mode: '0664'

  - name: copy the content of the web site
    copy:
      src: /root/github/web.html
      dest: /usr/share/nginx/html/web.html

  - name: restart nginx
    yum:
      name: nginx
      state: latest

#     name : start nodejs
#     name : change code
